from __future__ import annotations


H2CLIENT_SOURCE_INTERFACE_ALIASES = ("WLAN", "以太网")
H2CLIENT_CONNECTIONS_PER_SOURCE_IP = 1
H2CLIENT_HEALTHCHECK_URL = "https://show.bilibili.com/"
H2CLIENT_HEALTHCHECK_HOST = "show.bilibili.com"
H2CLIENT_HEALTHCHECK_TIMEOUT = 5.0
